FROM quay.io/lib/eclipse-temurin:21

WORKDIR /app

COPY joshsim-fat.jar /app/

EXPOSE 8085

CMD ["java", "-jar", "joshsim-fat.jar", "server", "--port=8085", "--concurrent-workers=5", "--use-http2=true", "--serial-patches", "--worker-url=\"https://josh-executor-dev-1007495489273.us-west1.run.app/runReplicate\""]
