FROM eclipse-temurin:21-jre

WORKDIR /app

COPY build/libs/joshsim-fat.jar /app/joshsim-fat.jar
COPY cloud-img/run-entrypoint.sh /app/run-entrypoint.sh
RUN chmod +x /app/run-entrypoint.sh

ENTRYPOINT ["/app/run-entrypoint.sh"]
