FROM quay.io/lib/eclipse-temurin:21

WORKDIR /app

COPY joshsim-fat.jar /app/

EXPOSE 8085

CMD ["java", "-jar", "joshsim-fat.jar", "server", "--port=8085", "--concurrent-workers=10", "--use-http2=true", "--worker-url=\"https://josh-executor-prod-1007495489273.us-west1.run.app\""]
