# Use an official OpenJDK runtime as a parent image
FROM openjdk:11

# Set the working directory
WORKDIR /workspaces/josh-specification

# Copy the repo contents
COPY . .

# Keep the container running
CMD tail -f /dev/null